### ISSUE TITLE
Sanitizing 'rude' words from the wordlist?

### ISSUE THREAD

**Issue by r4v5** [iphoting/pwqgen.rb#4]
Hi there, I love this gem and it's been pretty useful to me. I was generating a password for a coworker and it generated a password of `sexy=Piss-tribe+Flick`, which (while definitely memorable!) could definitely lead to an awkward situation. Nothing about the code seems to imply a need for this specific wordlist or length. Could it be swapped out with something like one of [the EFF's wordlists](https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases)? I'm not sure if you're trying to faithfully recreate `pwqgen` in ruby or just make a useful passphrase-generating tool, so if you're aiming for the former, feel free to close.

**Comment by iphoting** [comment]
Done in v0.1.0, commit a25e4397c06bb1c8c0efbc9633321742d1f0f2b0.
https://rubygems.org/gems/pwqgen.rb/versions/0.1.0

**Comment by r4v5** [comment]
Thank you so much for your fast response!
